import {
  Combine,
  Scissors,
  Minimize2,
  FileImage,
  ImagePlus,
  ArrowRightLeft,
  FileType,
  FileText,
  FileSpreadsheet,
  Presentation,
  Stamp,
} from 'lucide-react';

export const TOOL_LIST = [
  {
    id: 'merge',
    title: 'Merge PDF',
    description: 'Combine multiple PDF files into one document.',
    icon: Combine,
    endpoint: '/api/pdf/merge',
    inputName: 'files',
    allowMultiple: true,
    accept: '.pdf,application/pdf',
    cta: 'Merge now',
    mode: 'server-pdf',
  },
  {
    id: 'split',
    title: 'Split PDF',
    description: 'Extract selected pages by ranges like 1-3,5.',
    icon: Scissors,
    endpoint: '/api/pdf/split',
    inputName: 'file',
    allowMultiple: false,
    accept: '.pdf,application/pdf',
    cta: 'Split now',
    mode: 'server-pdf',
  },
  {
    id: 'compress',
    title: 'Compress PDF',
    description: 'Optimize PDF structure and output smaller files.',
    icon: Minimize2,
    endpoint: '/api/pdf/compress',
    inputName: 'file',
    allowMultiple: false,
    accept: '.pdf,application/pdf',
    cta: 'Compress now',
    mode: 'server-pdf',
  },
  {
    id: 'watermark',
    title: 'Add Watermark',
    description: 'Add centered watermark text on every PDF page.',
    icon: Stamp,
    endpoint: '/api/pdf/watermark',
    inputName: 'file',
    allowMultiple: false,
    accept: '.pdf,application/pdf',
    cta: 'Add watermark',
    mode: 'server-pdf',
  },
  {
    id: 'pdfToImage',
    title: 'PDF to Image',
    description: 'Convert PDF pages into PNG images (ZIP).',
    icon: FileImage,
    endpoint: '/api/pdf/pdf-to-image',
    inputName: 'file',
    allowMultiple: false,
    accept: '.pdf,application/pdf',
    cta: 'Convert now',
    mode: 'server-pdf',
  },
  {
    id: 'imageToPdf',
    title: 'Image to PDF',
    description: 'Convert one or more images into a single PDF.',
    icon: ImagePlus,
    endpoint: '/api/pdf/image-to-pdf',
    inputName: 'files',
    allowMultiple: true,
    accept: '.png,.jpg,.jpeg,.webp,image/png,image/jpeg,image/webp',
    cta: 'Create PDF',
    mode: 'server-pdf',
  },
  {
    id: 'png-to-jpg',
    title: 'PNG to JPG',
    description: 'Convert PNG image to JPG in browser.',
    icon: ArrowRightLeft,
    inputName: 'file',
    allowMultiple: false,
    accept: '.png,image/png',
    cta: 'Convert now',
    mode: 'client-image',
  },
  {
    id: 'jpg-to-png',
    title: 'JPG to PNG',
    description: 'Convert JPG image to PNG in browser.',
    icon: FileImage,
    inputName: 'file',
    allowMultiple: false,
    accept: '.jpg,.jpeg,image/jpeg,image/jpg',
    cta: 'Convert now',
    mode: 'client-image',
  },
  {
    id: 'png-to-ico',
    title: 'PNG to ICO',
    description: 'Create ICO icon (32 or 256 px) in browser.',
    icon: FileType,
    inputName: 'file',
    allowMultiple: false,
    accept: '.png,image/png',
    cta: 'Convert now',
    mode: 'client-image',
  },
  {
    id: 'word-to-pdf',
    title: 'Word to PDF',
    description: 'Convert DOC/DOCX to PDF using backend.',
    icon: FileText,
    endpoint: '/api/pdf/office-to-pdf',
    inputName: 'file',
    allowMultiple: false,
    accept: '.doc,.docx,application/msword,application/vnd.openxmlformats-officedocument.wordprocessingml.document',
    cta: 'Convert now',
    mode: 'server-office',
    officeKind: 'word',
  },
  {
    id: 'excel-to-pdf',
    title: 'Excel to PDF',
    description: 'Convert XLS/XLSX to PDF using backend.',
    icon: FileSpreadsheet,
    endpoint: '/api/pdf/office-to-pdf',
    inputName: 'file',
    allowMultiple: false,
    accept: '.xls,.xlsx,application/vnd.ms-excel,application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
    cta: 'Convert now',
    mode: 'server-office',
    officeKind: 'excel',
  },
  {
    id: 'ppt-to-pdf',
    title: 'PPT to PDF',
    description: 'Convert PPT/PPTX to PDF using backend.',
    icon: Presentation,
    endpoint: '/api/pdf/office-to-pdf',
    inputName: 'file',
    allowMultiple: false,
    accept: '.ppt,.pptx,application/vnd.ms-powerpoint,application/vnd.openxmlformats-officedocument.presentationml.presentation',
    cta: 'Convert now',
    mode: 'server-office',
    officeKind: 'ppt',
  },
];

export const TOOL_MAP = TOOL_LIST.reduce((acc, tool) => {
  acc[tool.id] = tool;
  return acc;
}, {});
